# Environment variables for lambda

default: &default
  <<: *default
  ENVIRONMENT: ${self:provider.stage}
  DB_NAME: ${self:custom.secrets.DB_NAME} # For TypeOrm DB Setup
  DB_USER: ${self:custom.secrets.DB_USER}
  DB_PASSWORD: ${self:custom.secrets.DB_PASSWORD}
  DB_HOST: ${self:custom.secrets.DB_HOST}
  DB_PORT: ${self:custom.secrets.DB_PORT}
  NODE_ENV: ${self:custom.secrets.NODE_ENV}
  IS_OFFLINE: true
Dev:
  <<: *default
  LoggerDebugLevel: debug
  IS_OFFLINE: False

Prod:
  <<: *default
  LoggerDebugLevel: info
  IS_OFFLINE: False
